# General
write_to_file: True
exps: [
  # 'pointmaze-umaze-dense-v2',
  # 'pointmaze-medium-dense-v2',
  # 'antmaze-umaze-v1',
  'd3il-avoiding',
  ]
n_trials: 10

# Environments
seeds: {
  'pointmaze-umaze-dense-v2': [7, 10, 11, 16, 24, 28, 31, 33, 39, 41, 43, 44, 45, 46, 48, 50, 53, 54, 59, 62, 66, 69, 71, 77, 80, 81, 84, 85, 87, 88, 97, 98, 103, 105, 107, 111, 112, 113, 119, 120, 122, 124, 126, 129, 130, 131, 139, 147, 149, 153, 155, 156, 165, 167, 168, 175, 176, 189, 193, 198]
}


dt: {
  'pointmaze': 0.02,
  'antmaze': 0.05,
  'avoiding': 1,    # Since a = [delta_x, delta_y] and not [vx, vy]
}
observation_indices: {
  'pointmaze': {'x': 0, 'y': 1, 'vx': 2, 'vy': 3, 'goal_x': 4, 'goal_y': 5},
  'antmaze': {'x': 0, 'y': 1, 'z':2, 'qx': 3, 'qy': 4, 'qz': 5, 'qw': 6, 'hip1': 7, 'ankle1': 8, 'hip2': 9, 'ankle2': 10, 
               'hip3': 11, 'ankle3': 12, 'hip4': 13, 'ankle4': 14, 'vx': 15, 'vy': 16, 'vz': 17, 'dhip1': 21, 'dankle1': 22,
               'dhip2': 23, 'dankle2': 24, 'dhip3': 25, 'dankle3': 26, 'dhip4': 27, 'dankle4': 28, 'goal_x': 29, 'goal_y': 30, },
  'avoiding': {'x_des': 0, 'y_des': 1, 'x': 2, 'y': 3},
}

action_indices: {
  'pointmaze': {'ax': 0, 'ay': 1},
  'antmaze': {},  # TODO
  'avoiding': {'vx': 0, 'vy': 1},
}

# Policy
diffusion_timestep_threshold: 0.2
repeat_last: 2

# Projection 
projection_variants: [
  # 'diffuser',     # this
  'post_processing', # this
  'no_dynamics', # this
  'ours-random',
  'ours-random-repeat',
  'ours-consistency',
  'ours-consistency-repeat',
  'ours-costs',
  'ours-costs-repeat',
]
projection_cost: 'pos_vel'
constraint_types: [
  'halfspace', 
  'obstacles', 
  'dynamics',
  'bounds',
  ]
enlarge_constraints: {
  'pointmaze': 0.05,
  'antmaze': 0.03,
}
halfspace_constraints: {
  'pointmaze-umaze-dense-v2': [
    # [[0.25, -1.5], [1.5, -0.25], 'above'], 
    [[1.5, 0.25], [0.25, 1.5], 'below'],
    ],
  'pointmaze-medium-dense-v2': [],
  'antmaze-umaze-v1': [
    # [[1.5, -6], [6, -1.5], 'above'], 
    # [[6, 1.5], [1.5, 6], 'below'],
    ],
  'd3il-avoiding': [
    # [[0.7, -0.3], [0.8, 0.5], 'above'],     # trivial
    # [[0.6, -0.3], [0.7, 0.5], 'above'],     # easy
    # [[0.75, -0.3], [0.3, 0.5], 'below'],   # hard (\ shape)
    # [[0.55, -0.3], [0.2, 0.5], 'below'],   # very hard (\ shape)
    [[0.25, -0.3], [0.7, 0.5], 'below'],     # hard (/ shape)
    # [[0.45, -0.3], [0.8, 0.5], 'below'],     # very hard (/ shape)
    ],
}
obstacle_constraints: {
  'pointmaze-umaze-dense-v2': [
    {'type': 'sphere_outside', 'dimensions': ['x', 'y'], 'center': [0.25, 1.0], 'radius': 0.1},
    {'type': 'sphere_outside', 'dimensions': ['x', 'y'], 'center': [1, -0.5], 'radius': 0.1},
    ],
    'pointmaze-medium-dense-v2': [
    {'type': 'sphere_outside', 'dimensions': ['x', 'y'], 'center': [-1.6, 0.5], 'radius': 0.1},
    {'type': 'sphere_outside', 'dimensions': ['x', 'y'], 'center': [1.5, -0.6], 'radius': 0.1},
    {'type': 'sphere_outside', 'dimensions': ['x', 'y'], 'center': [0.45, -1], 'radius': 0.1},
    ],
  'antmaze-umaze-v1': [
    {'type': 'sphere_outside', 'dimensions': ['x', 'y'], 'center': [4, 0], 'radius': 0.1},
    ],
  'd3il-avoiding': [
    # {'type': 'sphere_outside', 'dimensions': ['x', 'y'], 'center': [0.575, 0.08], 'radius': 0.1},  # second row, right obstacle larger
    {'type': 'sphere_outside', 'dimensions': ['x', 'y'], 'center': [0.5, -0.1], 'radius': 0.08},  # first row obstacle larger
  ]
}
bounds: {
  'pointmaze-umaze-dense-v2': [
    {'type': 'lower', 'dimensions': ['vx', 'vy'], 'values': [-4, -4]},
    {'type': 'upper', 'dimensions': ['vx', 'vy'], 'values': [4, 4]},
  ],
  'pointmaze-medium-dense-v2': [
    {'type': 'lower', 'dimensions': ['vx', 'vy'], 'values': [-4, -4]},
    {'type': 'upper', 'dimensions': ['vx', 'vy'], 'values': [4, 4]},
  ],  
  'antmaze-umaze-v1': [],
  'd3il-avoiding': [
    {'type': 'lower', 'dimensions': ['vx', 'vy'], 'values': [-0.01, 0]},
    {'type': 'upper', 'dimensions': ['vx', 'vy'], 'values': [0.01, 0.01]},
  ],
}

# Plotting
plot_how_many: 10
ax_limits: {
  'pointmaze-umaze-dense-v2': [[-1.5, 1.5], [-1.5, 1.5]],
  'pointmaze-medium-dense-v2': [[-3, 3], [-3, 3]],
  'pointmaze-large-dense-v2': [[-5, 5], [-5, 5]],    # Actually [-5, -3.5], [3.5, 5]
  'antmaze-umaze-v1': [[-6, 6], [-6, 6]],
  'antmaze-medium-diverse-v1': [[-12, 12],[-12, 12]],
  'antmaze-medium-diverse-v1': [[-20, 20], [-20, 20]], # Actually [-20, -14], [14, 20]
  'd3il-avoiding': [[0.2, 0.8], [-0.3, 0.5]]
}
