# General
exps: ['pointmaze-umaze-dense-v2']
n_trials: 5

# Environments
seeds: {
  'pointmaze-umaze-dense-v2': [7, 10, 11, 16, 24, 28, 31, 33, 39, 41, 43, 44, 45, 46, 48],
}
n_timesteps: {
  'pointmaze-umaze-dense-v2': 100,
  'antmaze-umaze-v1': 300
}

dt: {
  'pointmaze': 0.02,
  'antmaze': 0.05
}
observation_indices: {
  'pointmaze': {'x': 0, 'y': 1, 'vx': 2, 'vy': 3, 'goal_x': 4, 'goal_y': 5},
  'antmaze': {'x': 0, 'y': 1, 'z':2, 'qx': 3, 'qy': 4, 'qz': 5, 'qw': 6, 'hip1': 7, 'ankle1': 8, 'hip2': 9, 'ankle2': 10, 
               'hip3': 11, 'ankle3': 12, 'hip4': 13, 'ankle4': 14, 'vx': 15, 'vy': 16, 'vz': 17, 'dhip1': 21, 'dankle1': 22,
               'dhip2': 23, 'dankle2': 24, 'dhip3': 25, 'dankle3': 26, 'dhip4': 27, 'dankle4': 28, 'goal_x': 29, 'goal_y': 30, }
}

# Policy
diffusion_timestep_threshold: 0.2
repeat_last: 0

# Projection 
projection_cost: 'pos_vel'
constraint_types: [
  # 'halfspace', 
  'obstacles', 
  'dynamics'
  ]
enlarge_constraints: {
  'pointmaze-umaze-dense-v2': 0.1,
  'antmaze-umaze-v1': 0.1
}
halfspace_constraints: {
  'pointmaze-umaze-dense-v2': [[[0.25, -1.5], [1.5, -0.25], 'above'], [[1.5, 0.25], [0.25, 1.5], 'below']],
  'antmaze-umaze-v1': [[[1.5, -6], [6, -1.5], 'above'], [[6, 1.5], [1.5, 6], 'below']]
}
obstacle_constraints: {
  'pointmaze-umaze-dense-v2': [{'type': 'sphere_outside', 'dimensions': ['x', 'y'], 'center': [1, 0], 'radius': 0.1}],
  'antmaze-umaze-v1': [{'type': 'sphere_outside', 'dimensions': ['x', 'y'], 'center': [4, 0], 'radius': 0.1}],
}

# Plotting
